/**
 * lang.js — Multi-language strings for NETVXL Telegram Bot
 * Supported: en (English — default), ar (Arabic), fr (French)
 */

const STRINGS = {

    // ─────────────────────────────────────────────
    // ENGLISH (default)
    // ─────────────────────────────────────────────
    en: {
        // Main menu
        main_title: '🎬 *NETVXL — Management Console*',
        main_body: [
            '',
            '👋 Welcome to the Netflix CDK Management System',
            '',
            '🔑 *CDK* — Create & manage subscription keys',
            '🍪 *Cookies* — Upload & verify Netflix accounts',
            '⚙️ *Settings* — Configure auto-check & limits',
        ].join('\n'),

        btn_cdk:      '🔑 CDK Management',
        btn_cookies:  '🍪 Cookie Management',
        btn_settings: '⚙️ Settings',
        btn_users: '👥 User Management',
        btn_back:     '⬅️ Back to Main Menu',
        btn_back_users: '⬅️ Back to Users',
        btn_back_cdk:     '⬅️ Back to CDK',
        btn_back_cookies: '⬅️ Back to Cookies',
        btn_back_settings:'⬅️ Back to Settings',
        btn_home:     '⬅️ Main Menu',
        btn_cancel:   '❌ Cancel',
        btn_confirm:  '✅ Confirm',

        // CDK Menu
        cdk_menu_title: '🔑 *CDK Key Management*\n\nChoose an action:',
        btn_cdk_create:     '➕ Create CDK Keys',
        btn_cdk_check:      '🔍 Check CDK Key',
        btn_cdk_list:       '📋 Last 50 Keys',
        btn_cdk_delete:     '❌ Delete Key',
        btn_cdk_delete_all: '🗑️ Delete All',

        // CDK Create wizard
        cdk_create_step1: '🔑 *Create CDK Keys*\n\n*Step 1/4:* Choose the plan type:',
        cdk_create_step2: '🔑 *Create CDK Keys*\n\n✅ Plan: *{plan}*\n\n*Step 2/4:* Choose the warranty pool / duration:',
        cdk_create_step3: '🔑 *Create CDK Keys*\n\n✅ Plan: *{plan}*\n✅ Warranty: *{warranty}*\n\n*Step 3/4:* Choose the allocation mode:',
        cdk_create_step3_random: '🔑 *Create CDK Keys*\n\n✅ Plan: *{plan}*\n✅ Warranty: *{warranty}*\n✅ Mode: *🎲 Random from Pool*\n\n*Step 4/4:* Choose quantity:',
        cdk_create_step3_specific: '🔑 *Create CDK Keys*\n\n✅ Plan: *{plan}*\n✅ Warranty: *{warranty}*\n✅ Mode: *📌 Specific Account*\n\nChoose the Netflix account:',
        cdk_create_step4_bound: '🔑 *Create CDK Keys*\n\n✅ Plan: *{plan}*\n✅ Warranty: *{warranty}*\n✅ Account: *{id}*\n\n*Step 4/4:* Choose quantity:',
        cdk_create_custom_qty: '🔑 *Create CDK Keys*\n\n✅ Plan: *{plan}*\n✅ Warranty: *{warranty}*\n\n✏️ Send the number of keys to generate:',
        cdk_no_active_accounts: '❌ No active accounts found to bind.\n\nChoose Random Pool Allocation instead.',
        cdk_generated: '🔑 *{count} CDK Key(s) Generated*\n\n✅ Plan: *{plan}*\n🛡️ Warranty: *{warranty}*\n📅 Duration: *{duration}*\n{bind}\n\n{keys}',
        cdk_bind_random: '\n🎲 *Allocation:* Random from Pool',
        cdk_bind_specific: '\n📌 *Bound Account:* {id}',
        cdk_duration_unlimited: 'Unlimited',
        cdk_duration_days: '{days} days',

        // CDK List
        cdk_list_title: '📋 *Last {count} CDK Keys:*\n\n',
        cdk_list_empty: 'No CDK keys found.',

        // CDK Check
        cdk_check_prompt: '🔍 *Check CDK Key*\n\nSend the key to verify:',
        cdk_check_notfound: '❌ Key `{key}` not found.',
        cdk_check_result: [
            '🔑 *Key Details*', '',
            '🔑 Key: `{key}`',
            '📋 Plan: *{plan}*',
            '{icon} Status: *{status}*',
            '🛡️ Warranty: *{warranty}*',
            '👥 Devices: *{active}/{max}*',
            '📱 Used on: *{device}*',
            '📧 Account: {email}',
            '📅 Created: *{date}*',
        ].join('\n'),
        cdk_status_unused: 'Unused',
        cdk_status_used:   'Used',
        cdk_device_none:   'Not used yet',
        cdk_email_none:    'Not assigned',

        // CDK Delete
        cdk_delete_prompt: '❌ *Delete CDK Key*\n\nSend the key to delete:',
        cdk_delete_success: '✅ Key `{key}` deleted successfully.',
        cdk_delete_notfound: '❌ Key `{key}` not found.',

        // CDK Delete All
        cdk_delete_all_confirm: '⚠️ *Warning!*\n\nAll CDK keys and activation logs will be permanently deleted.\n\nAre you sure?',
        cdk_delete_all_success: '✅ All CDK keys and activation logs have been deleted.',

        // Cookies Menu
        cookies_menu_title: '🍪 *Cookie Management*\n\nChoose a pool to upload cookies, or view stats:',
        btn_cook_stats:  '📊 Cookie Statistics',
        btn_cook_verify: '🔄 Verify All Accounts',
        btn_cook_dead_cdks: '⚠️ Compensation (Dead Cookies)',
        btn_cook_delete: '❌ Delete Account (Cookie)',
        btn_cook_delete_all: '🗑️ Delete All Cookies',
        btn_cook_delete_dead: '🗑️ Delete Expired (Dead) Cookies',
        btn_cook_divider:'─── Upload by Category ───',
        cook_delete_prompt: '❌ *Delete Account (Cookie)*\n\nSend the Email address of the account you want to delete:',
        cook_delete_success: '✅ Deleted account `{email}` successfully.',
        cook_delete_notfound: '❌ Account with Email `{email}` was not found.',
        cook_delete_all_confirm: '⚠️ *Warning!*\n\nThis will permanently delete ALL cookie files from the system.\n\nAre you sure you want to proceed?',
        cook_delete_all_success: '✅ Successfully deleted all cookies ({count} accounts).',
        cook_delete_dead_success: '✅ Successfully deleted {count} expired (dead) cookies.',
        cook_delete_dead_empty: 'ℹ️ No expired (dead) cookies found to delete.',
        cook_stats_title: '📊 *Active Accounts & Slots List*\n\nSelect an account below to view details, change slots capacity, move warranty pool, or delete it:',
        cook_manage_title: '📧 *Manage Account*\n\n📧 Email: `{email}`\n📋 Plan: *{plan}*\n🛡️ Warranty Pool: *{pool}*\n👥 Capacity/Slots: *{active}/{max}* users\n📅 Netflix Billing Expiry: *{billing}*',
        cook_manage_billing_days: '`{date}` (*{days} days remaining*)',
        cook_manage_billing_unknown: '`{date}` (*Partner billing / Unknown*)',
        btn_cook_change_slots: '👥 Change Slots Limit',
        btn_cook_change_pool: '🛡️ Change Warranty Pool',
        btn_cook_verify_single: '🔄 Verify This Account',
        btn_cook_back_list: '🔙 Back to Accounts',
        cook_verify_single_start: '⏳ *Verifying account `{email}`...*',
        cook_verify_single_ok: '✅ *Account `{email}` is Active & Working!*\n\n📋 Plan: *{plan}*\n📅 Expiry: *{billing}*',
        cook_verify_single_fail: '❌ *Account `{email}` is Dead / Expired!*\n\nStatus updated to Expired in system.',
        cook_change_slots_prompt: '👥 *Change Slots Limit*\n\nSend the new maximum user slots limit (e.g., 5, 10, 15, 20) for account `{email}`:',
        cook_change_slots_success: '✅ Successfully updated slots capacity to *{n}* for account `{email}`.',
        cook_change_pool_title: '🛡️ *Change Warranty Pool*\n\nSelect the new warranty pool for account `{email}`:',
        cook_change_pool_success: '✅ Successfully moved account `{email}` to pool: *{pool}*.',
        cook_delete_one_confirm: '⚠️ *Delete Account Confirmation*\n\nAre you sure you want to delete account `{email}`? This will unbind all its active CDK keys!',

        // User Management (English)
        users_title: '👥 *User Management*\n\nHere you can authorize partners or CDK creators:',
        btn_users_add_partner: '➕ Add Partner',
        btn_users_add_creator: '➕ Add CDK Creator',
        btn_users_list: '📋 List Users',
        btn_users_delete: '❌ Remove User',
        users_add_partner_prompt: '👤 *Add Partner*\n\nSend the Telegram Chat ID of the partner to add:',
        users_add_creator_prompt: '👤 *Add CDK Creator*\n\nSend the Telegram Chat ID of the CDK creator to add:',
        users_delete_prompt: '❌ *Remove User*\n\nSend the Telegram Chat ID of the user to remove:',
        users_add_success: '✅ Authorized Chat ID `{id}` as *{role}*.',
        users_delete_success: '✅ Removed user Chat ID `{id}`.',
        users_list_title: '📋 *Authorized Users:*',
        users_list_empty: 'No authorized users found.',
        users_list_row: '• ID: `{id}` | Role: *{role}* | Added: {date}',
        error_no_permission: '❌ Permission Denied. You do not have access to this feature.',
        cdk_gen_no_stock: '❌ *Generation Blocked (No Stock)*\n\nCannot generate {requested} keys.\n\nPlan: *{plan}*\nWarranty: *{warranty}*\nAvailable Slots/Stock: *{available}* slots.\n\nPlease upload more cookies/accounts to this pool first!',
        error_raw_cookie_paste: '❌ *Invalid Operation*\n\nYou sent raw cookie text. Please go to *Cookie Management*, select the correct category/warranty pool, and upload your cookies there as a file!',


        // Dead CDK Compensation
        cook_dead_title: '⚠️ *Compensation & Stopped Accounts*\n\nHere are the accounts that stopped working, along with the CDK keys assigned to them:',
        cook_dead_empty: '✅ No stopped/expired accounts found at the moment.',
        cook_dead_row: '\n• ❌ *{email}* ({pool})\n  Checked: {date}\n  🔑 *CDK Keys:*',
        cook_dead_key: '    - `{key}` ({status} | Device: {device} | Active: {active})',


        // Cookie Upload
        cook_pool_prompt: '🍪 *Upload Cookies — {pool}*\n\n📤 Send one or more .txt files with cookie data.\n\n💡 You can send multiple files at once for batch import.',
        cook_no_file: '⚠️ Please first choose a warranty category from *🍪 Cookie Management*, then send the file.',
        cook_downloading: '⏳ Downloading {count} file(s)...',
        cook_processing: '✅ Downloaded *{count}* file(s)\n🍪 Pool: *{pool}*\n\n⏳ Processing and verifying...',
        cook_download_fail: '❌ Failed to download files. Please try again.',
        cook_checking: '⏳ Checking {count} account(s)...',
        cook_import_result: [
            '✅ *Import Complete — {source}*',
            '🍪 Pool: *{pool}*', '',
            '• Total: *{total}*',
            '• New accounts: *{added}*',
            '• Replaced (duplicate): *{replaced}*',
            '• Expired / Invalid: *{bad}*',
        ].join('\n'),
        cook_import_new:      '\n*New Accounts:*',
        cook_import_replaced: '\n*Replaced:*',

        // Cookie Stats
        cook_stats_title: '📊 *Cookie Statistics by Pool*\n\n• Total Active: *{active}* | Expired: *{expired}* | All: *{total}*\n',
        cook_stats_empty: '📊 No cookies stored yet.\n\nGo to *🍪 Cookie Management* and choose a pool to upload cookies.',
        cook_stats_row: '{pool}\n  🟢 Active: {active}  |  🔴 Expired: {expired}',
        cook_stats_header: '\n\n─── *Active Accounts & Slots* ───',
        cook_stats_item: '• *#{id}* - {email} ({plan})\n  🛡️ Pool: {pool} | 👥 Reserved: *{active}/{max}* users',


        // Cookie Verify
        cook_verify_start: '🔄 *Verifying all accounts...*\n\nThis may take a while.',
        cook_verify_result: [
            '✅ *Verification Complete*', '',
            '🟢 Active: *{active}* | 🔴 Expired: *{expired}* | Total: *{total}*',
        ].join('\n'),
        cook_verify_expired:  '\n*🔴 Expired:*',
        cook_verify_expiring: '\n*⚠️ Expiring Soon:*',
        cook_verify_empty: 'No cookies to check.',

        // Settings
        settings_title: '⚙️ *System Settings*\n\n• Max users per cookie: *{max}*\n• Auto-check: *{auto}*\n• Language: *{lang}*\n• Proxy: *{proxy}*\n\nChoose a setting to modify:',
        btn_set_max:  '👥 Change Max Users per Cookie',
        btn_set_auto: '⏱️ Auto-Check Interval',
        btn_set_lang: '🌐 Language / اللغة / Langue',
        btn_set_proxy:'🌐 Proxy Settings',
        set_max_prompt: '👥 *Max Users per Cookie*\n\nCurrent limit: *{cur}* users per account.\n\nSend the new limit (number):',
        set_max_success: '✅ *Updated!*\n\n• Max users per cookie: *{n}*\n• Applied to all existing accounts.',
        set_auto_title: '⏱️ *Auto Cookie Check*\n\nCurrent interval: *{cur}*\n\nChoose the new interval:',
        set_auto_disabled: '🚫 Disabled',
        set_auto_every: 'Every {h} hour(s)',
        set_auto_btn: '⚡ Every {h}h',
        set_auto_off: '🚫 Off',
        set_auto_success: '✅ *Updated!*\n\n• Auto-check: *{val}*',
        set_lang_title: '🌐 *Language Selection*\n\nChoose your preferred language:',
        set_lang_success: '✅ Language set to *{lang}*',
        auto_check_label: 'Every {h} hour(s)',
        auto_check_off: 'Off (Disabled)',

        // Proxy
        proxy_menu_title: '🌐 *Proxy Settings*\n\n• Status: *{status}*\n• Mode: *{mode}*\n• URL: `{url}`\n• Failures: *{fails}/{max}*\n\nChoose an action:',
        proxy_status_on:    '🟢 Enabled',
        proxy_status_off:   '🔴 Disabled',
        proxy_mode_proxy:   '🌐 Via Proxy',
        proxy_mode_local:   '🏠 Local IP',
        proxy_url_none:     'Not configured',
        btn_proxy_check_ip: '🔍 Check Current IP',
        btn_proxy_add:      '➕ Add / Replace Proxy',
        btn_proxy_enable:   '🟢 Enable Proxy',
        btn_proxy_disable:  '🔴 Disable Proxy',
        btn_proxy_delete:   '🗑️ Remove Proxy',
        btn_proxy_local:    '🏠 Use Local IP',
        proxy_add_prompt:   '➕ *Add / Replace Proxy*\n\nSend the proxy URL in one of these formats:\n• `http://host:port`\n• `http://user:pass@host:port`\n• `socks5://host:port`\n• `socks5://user:pass@host:port`',
        proxy_testing:      '⏳ Testing proxy connection...',
        proxy_test_ok:      '✅ *Proxy Connected!*\n\n• IP via Proxy: `{ip}`\n• Proxy saved and enabled.',
        proxy_test_fail:    '❌ *Proxy Test Failed*\n\nError: `{error}`\n\nCheck the proxy URL and try again.',
        proxy_invalid_url:  '❌ Invalid proxy URL: `{reason}`\n\nTry again:',
        proxy_enabled_ok:   '✅ Proxy *enabled*. All requests will use the proxy.',
        proxy_disabled_ok:  '✅ Proxy *disabled*. Using local IP.',
        proxy_deleted_ok:   '✅ Proxy removed successfully.',
        proxy_checking_ip:  '⏳ Checking IP address...',
        proxy_ip_result:    '🌐 *Current IP Address*\n\n• Mode: *{mode}*\n• IP: `{ip}`',
        proxy_ip_fail:      '❌ Could not determine IP address.',
        proxy_fallback_alert: '⚠️ *Proxy Failure Alert*\n\nThe proxy `{url}` has failed *{fails}* consecutive times.\n\n🔄 Automatically switched to *Local IP* mode.\n\nPlease update or disable the proxy in ⚙️ Settings → 🌐 Proxy.',
        proxy_no_proxy:     'Not configured',

        // Alloc / Plan / Pool labels
        plan_label: { Premium: '👑 Premium 4K', Standard: '📺 Standard 1080p', Basic: '📱 Basic', TV: '🖥️ TV Screen' },
        pool_label: {
            no_warranty: '🚫 No Warranty',
            '7_days':    '⚡ 7 Days',
            '1_month':   '🗓️ 1 Month',
            '2_months':  '🗓️ 2 Months',
            '3_months':  '🗓️ 3 Months',
            '6_months':  '🗓️ 6 Months',
            '1_year':    '👑 1 Year',
        },
        alloc_random:   '🎲 Random from Pool (Default)',
        alloc_specific: '📌 Specific Account (Choose ID)',
        error_db:       '❌ Database error.',
        error_number:   '❌ Please send a valid positive number:',
        unauthorized:   '🚫 Unauthorized.',
        // Customer strings
        cust_select_lang: '👋 Welcome! Please choose your preferred language / الرجاء اختيار لغة البوت:',
        cust_join_channel: '❌ You must join our Telegram Channel first to use the bot:\n👉 {channel}\n\nOnce joined, click the button below to verify:',
        cust_btn_verify: '✅ Verify Subscription',
        cust_btn_verify_success: '🎉 Thank you for joining! You received 1 point.',
        cust_main_menu: '🎬 <b>Netflix CDK Portal</b>\n\n💰 <b>Your Points:</b> {points}\n👥 <b>Invites Progress:</b> {ref_count}/3\n\n🔗 <b>Your Referral Link:</b>\n<code>{ref_link}</code>',
        cust_btn_get_cdk: '🎁 Get CDK Key',
        cust_btn_lang: '🌐 Change Language',
        cust_btn_support: '📞 Support',
        cust_btn_back: '⬅️ Retour',
        cust_btn_back: '⬅️ Back',
        cust_support_msg: '📩 For any inquiries or support, contact the admin here: {admin}',
        cust_cookies_updated: '🎉 <b>New Netflix accounts have been added to the bot!</b> 🎬🍿\n\nWhat are you waiting for? Share the bot and collect points to get your activation key for free! 🎁👇\n\nYour referral link:\n<code>{ref_link}</code>',
        cust_daily_broadcast: '⚡ <b>What are you waiting for?</b> Share your referral link and collect points to get a free Netflix account! 🎬🎁\n\nYour referral link:\n<code>{ref_link}</code>',
        cust_left_channel_warning: '⚠️ <b>You left the channel!</b>\n\nYour points: <b>{points}</b> (-1 penalty)\n\nRejoin to restore your point.',
        cust_rejoined_channel: '👋 <b>Welcome back!</b>\n\nPoints restored: <b>{points}</b>\n\n❌ No new CDK — you left before. Keep earning via referrals!',
        cust_not_enough_points: '❌ You do not have enough points (1 point required).\n\nInvite 3 friends to earn 1 point! Share your referral link:\n<code>{ref_link}</code>',
        cust_ref_notify: '🔔 Someone has joined the bot using your link! ({ref_count}/3 invites for next point)\n💰 Your current points: <b>{points}</b>',
        cust_ref_point_reward: '🎉 Congratulations! You invited 3 friends and earned 1 point! Your total points: {points}',
        cust_cdk_success: '🔑 <b>Your Netflix CDK Key:</b>\n\n<code>{key}</code>\n\nPlan: <b>{plan}</b>\n\n👉 Go to our portal to activate it!',
        admin_btn_analytics: '👥 Customer Analytics',
        admin_analytics_title: '📊 *Customer Analytics*\n\n👥 Total Registered Customers: *{total_users}*\n💰 Total Points Distributed: *{total_points}*\n\n📋 *Latest Users:*',
        admin_analytics_user_row: '👤 @{username} (ID: `{id}`) | Points: *{points}* | Invites: *{invites}* | Joined: {date}',

    },

    // ─────────────────────────────────────────────
    // ARABIC
    // ─────────────────────────────────────────────
    ar: {
        main_title: '🎬 *NETVXL — لوحة التحكم*',
        main_body: [
            '',
            '👋 مرحباً بك في منظومة إدارة Netflix CDK',
            '',
            '🔑 *CDK* — إنشاء وإدارة مفاتيح الاشتراك',
            '🍪 *كوكيز* — رفع وفحص حسابات النتفليكس',
            '⚙️ *إعدادات* — ضبط الفحص التلقائي والحدود',
        ].join('\n'),

        btn_cdk:      '🔑 إدارة CDK',
        btn_cookies:  '🍪 إدارة الكوكيز',
        btn_settings: '⚙️ الإعدادات',
        btn_users: '👥 إدارة الأعضاء',
        btn_back:     '⬅️ رجوع للرئيسية',
        btn_back_users: '⬅️ رجوع لإدارة الأعضاء',
        btn_back_cdk:     '⬅️ رجوع لإدارة CDK',
        btn_back_cookies: '⬅️ رجوع لإدارة الكوكيز',
        btn_back_settings:'⬅️ رجوع للإعدادات',
        btn_home:     '⬅️ الرئيسية',
        btn_cancel:   '❌ إلغاء',
        btn_confirm:  '✅ تأكيد',

        cdk_menu_title: '🔑 *إدارة مفاتيح CDK*\n\nاختر العملية المطلوبة:',
        btn_cdk_create:     '➕ إنشاء مفاتيح CDK',
        btn_cdk_check:      '🔍 فحص مفتاح CDK',
        btn_cdk_list:       '📋 آخر 50 مفتاح',
        btn_cdk_delete:     '❌ حذف مفتاح',
        btn_cdk_delete_all: '🗑️ حذف الكل',

        cdk_create_step1: '🔑 *إنشاء مفاتيح CDK*\n\n*الخطوة 1/4:* اختر نوع الخطة:',
        cdk_create_step2: '🔑 *إنشاء مفاتيح CDK*\n\n✅ الخطة: *{plan}*\n\n*الخطوة 2/4:* اختر فئة الضمان والمدة:',
        cdk_create_step3: '🔑 *إنشاء مفاتيح CDK*\n\n✅ الخطة: *{plan}*\n✅ الضمان: *{warranty}*\n\n*الخطوة 3/4:* اختر طريقة التخصيص:',
        cdk_create_step3_random: '🔑 *إنشاء مفاتيح CDK*\n\n✅ الخطة: *{plan}*\n✅ الضمان: *{warranty}*\n✅ النوع: *🎲 عشوائي من الحوض*\n\n*الخطوة 4/4:* اختر الكمية:',
        cdk_create_step3_specific: '🔑 *إنشاء مفاتيح CDK*\n\n✅ الخطة: *{plan}*\n✅ الضمان: *{warranty}*\n✅ النوع: *📌 حساب محدد*\n\nاختر الحساب:',
        cdk_create_step4_bound: '🔑 *إنشاء مفاتيح CDK*\n\n✅ الخطة: *{plan}*\n✅ الضمان: *{warranty}*\n✅ الحساب: *{id}*\n\n*الخطوة 4/4:* اختر الكمية:',
        cdk_create_custom_qty: '🔑 *إنشاء مفاتيح CDK*\n\n✅ الخطة: *{plan}*\n✅ الضمان: *{warranty}*\n\n✏️ أرسل الكمية المطلوبة (رقم):',
        cdk_no_active_accounts: '❌ لا توجد حسابات نشطة للربط بها.\n\nاختر الوضع العشوائي بدلاً من ذلك.',
        cdk_generated: '🔑 *تم توليد {count} مفتاح CDK*\n\n✅ الخطة: *{plan}*\n🛡️ الضمان: *{warranty}*\n📅 المدة: *{duration}*\n{bind}\n\n{keys}',
        cdk_bind_random: '\n🎲 *التخصيص:* عشوائي من الحوض',
        cdk_bind_specific: '\n📌 *الحساب المرتبط:* {id}',
        cdk_duration_unlimited: 'بدون حد',
        cdk_duration_days: '{days} يوم',

        cdk_list_title: '📋 *آخر {count} مفتاح CDK:*\n\n',
        cdk_list_empty: 'لا توجد مفاتيح CDK حتى الآن.',

        cdk_check_prompt: '🔍 *فحص مفتاح CDK*\n\nأرسل المفتاح للتحقق منه:',
        cdk_check_notfound: '❌ المفتاح `{key}` غير موجود.',
        cdk_check_result: [
            '🔑 *تفاصيل المفتاح*', '',
            '🔑 المفتاح: `{key}`',
            '📋 الخطة: *{plan}*',
            '{icon} الحالة: *{status}*',
            '🛡️ الضمان: *{warranty}*',
            '👥 الأجهزة: *{active}/{max}*',
            '📱 الجهاز: *{device}*',
            '📧 الحساب: {email}',
            '📅 تاريخ الإنشاء: *{date}*',
        ].join('\n'),
        cdk_status_unused: 'غير مستخدم',
        cdk_status_used:   'مستخدم',
        cdk_device_none:   'لم يُستخدم',
        cdk_email_none:    'غير مُخصص',

        cdk_delete_prompt: '❌ *حذف مفتاح CDK*\n\nأرسل المفتاح المراد حذفه:',
        cdk_delete_success: '✅ تم حذف المفتاح `{key}` بنجاح.',
        cdk_delete_notfound: '❌ المفتاح `{key}` غير موجود.',

        cdk_delete_all_confirm: '⚠️ *تحذير!*\n\nسيتم حذف جميع مفاتيح CDK وسجلات التفعيل بشكل نهائي.\n\nهل أنت متأكد؟',
        cdk_delete_all_success: '✅ تم حذف جميع مفاتيح CDK وسجلات التفعيل بنجاح.',

        cookies_menu_title: '🍪 *إدارة الكوكيز*\n\nاختر فئة لرفع الكوكيز إليها، أو اعرض الإحصائيات:',
        btn_cook_stats:  '📊 إحصائيات الكوكيز',
        btn_cook_verify: '🔄 فحص جميع الكوكيز',
        btn_cook_dead_cdks: '⚠️ التعويض (الحسابات المتوقفة)',
        btn_cook_delete: '❌ حذف حساب (كوكيز)',
        btn_cook_delete_all: '🗑️ حذف جميع الكوكيز',
        btn_cook_delete_dead: '🗑️ حذف الحسابات المتوقفة فقط',
        btn_cook_divider:'─── رفع كوكيز حسب الفئة ───',
        cook_delete_prompt: '❌ *حذف حساب (كوكيز)*\n\nأرسل البريد الإلكتروني (Email) للحساب المراد حذفه:',
        cook_delete_success: '✅ تم حذف الحساب \`{email}\` بنجاح.',
        cook_delete_notfound: '❌ لم يتم العثور على حساب بالبريد \`{email}\`.',
        cook_delete_all_confirm: '⚠️ *تحذير!*\n\nسيؤدي هذا الإجراء إلى حذف جميع ملفات الكوكيز والحسابات من النظام نهائياً.\n\nهل أنت متأكد من رغبتك في الاستمرار؟',
        cook_delete_all_success: '✅ تم حذف جميع الكوكيز بنجاح ({count} حساب).',
        cook_delete_dead_success: '✅ تم حذف {count} حساب متوقف بنجاح.',
        cook_delete_dead_empty: 'ℹ️ لا توجد حسابات متوقفة لحذفها.',
        cook_stats_title: '📊 *قائمة الحسابات والفتحات النشطة*\n\nاختر حساباً من القائمة أدناه لعرض تفاصيله، أو لتغيير حد الفتحات، أو لنقله لفئة ضمان أخرى، أو لحذفه:',
        cook_manage_title: '📧 *إدارة الحساب*\n\n📧 البريد: `{email}`\n📋 الاشتراك: *{plan}*\n🛡️ فئة الضمان: *{pool}*\n👥 الاستيعاب/الفتحات: *{active}/{max}* مستخدم\n📅 انتهاء فوترة نيتفلكس: *{billing}*',
        cook_manage_billing_days: '`{date}` (*متبقي {days} يوم*)',
        cook_manage_billing_unknown: '`{date}` (*شريك فوترة / غير محدد*)',
        btn_cook_change_slots: '👥 تعديل حد الفتحات',
        btn_cook_change_pool: '🛡️ نقل فئة الضمان',
        btn_cook_verify_single: '🔄 فحص هذا الحساب',
        btn_cook_back_list: '🔙 العودة لقائمة الحسابات',
        cook_verify_single_start: '⏳ *جاري فحص الحساب `{email}`...*',
        cook_verify_single_ok: '✅ *الحساب `{email}` نشط ويعمل!*\n\n📋 الاشتراك: *{plan}*\n📅 تاريخ انتهاء الفوترة: *{billing}*',
        cook_verify_single_fail: '❌ *الحساب `{email}` متوقف أو غير صالح!*\n\nتم تحديث حالة الحساب في النظام إلى "منتهي".',
        cook_change_slots_prompt: '👥 *تعديل حد الفتحات*\n\nأرسل الحد الأقصى الجديد للفتحات (مثلاً: 5، 10، 15، 20) للحساب `{email}`:',
        cook_change_slots_success: '✅ تم تعديل حد الفتحات إلى *{n}* للحساب `{email}` بنجاح.',
        cook_change_pool_title: '🛡️ *نقل فئة الضمان*\n\nاختر فئة الضمان الجديدة للحساب `{email}`:',
        cook_change_pool_success: '✅ تم نقل الحساب `{email}` إلى فئة *{pool}* بنجاح.',
        cook_delete_one_confirm: '⚠️ *تأكيد حذف الحساب*\n\nهل أنت متأكد من رغبتك في حذف الحساب `{email}`؟ سيؤدي هذا إلى إلغاء ربطه من جميع مفاتيح CDK النشطة التابعة له!',

        // User Management (Arabic)
        users_title: '👥 *إدارة الأعضاء والصلاحيات*\n\nهنا يمكنك إضافة شركاء أو موزعي مفاتيح وتخويلهم:',
        btn_users_add_partner: '➕ إضافة شريك',
        btn_users_add_creator: '➕ إضافة موزع مفاتيح',
        btn_users_list: '📋 قائمة الأعضاء المخولين',
        btn_users_delete: '❌ إزالة عضو',
        users_add_partner_prompt: '👤 *إضافة شريك*\n\nأرسل المعرف (Chat ID) للشريك المراد إضافته:',
        users_add_creator_prompt: '👤 *إضافة موزع مفاتيح*\n\nأرسل المعرف (Chat ID) للموزع المراد إضافته:',
        users_delete_prompt: '❌ *إزالة عضو*\n\nأرسل المعرف (Chat ID) للعضو المراد إزالته:',
        users_add_success: '✅ تم إضافة العضو بالمعرف \`{id}\` برتبة *{role}* بنجاح.',
        users_delete_success: '✅ تم إزالة العضو بالمعرف \`{id}\` بنجاح.',
        users_list_title: '📋 *الأعضاء المخولين:*',
        users_list_empty: 'لا يوجد أعضاء مخولين حالياً.',
        users_list_row: '• معرف: \`{id}\` | الرتبة: *{role}* | أضيف: {date}',
        error_no_permission: '❌ ليس لديك صلاحية للوصول إلى هذه الميزة.',
        unauthorized: '🚫 غير مصرح لك.',
        cdk_gen_no_stock: '❌ *تم إيقاف الإنشاء (لا يوجد مخزون)*\n\nلا يمكن توليد {requested} مفتاح.\n\nالاشتراك: *{plan}*\nالضمان: *{warranty}*\nالفتحات المتاحة/المخزون: *{available}* فتحة.\n\nيرجى رفع المزيد من الحسابات/الكوكيز إلى هذه الفئة أولاً!',
        error_raw_cookie_paste: '❌ *عملية غير صالحة*\n\nلقد أرسلت نص كوكيز مباشر. يرجى الذهاب إلى *إدارة الكوكيز*، واختيار الفئة/الضمان المناسب، ورفع الكوكيز كملف هناك!',

        // Dead CDK Compensation (Arabic)
        cook_dead_title: '⚠️ *التعويض والحسابات المتوقفة*\n\nإليك الحسابات التي توقفت عن العمل، مع مفاتيح CDK المرتبطة بها:',
        cook_dead_empty: '✅ لا توجد حسابات متوقفة حالياً.',
        cook_dead_row: '\n• ❌ *{email}* ({pool})\n  تاريخ الفحص: {date}\n  🔑 *مفاتيح CDK:*',
        cook_dead_key: '    - `{key}` ({status} | الجهاز: {device} | نشط: {active})',


        cook_pool_prompt: '🍪 *رفع كوكيز — {pool}*\n\n📤 أرسل ملف (.txt) أو أكثر يحتوي على بيانات الكوكيز.\n\n💡 يمكنك إرسال عدة ملفات في آن واحد للاستيراد الجماعي.',
        cook_no_file: '⚠️ اختر أولاً فئة الضمان من قسم *🍪 إدارة الكوكيز* ثم أرسل الملف.',
        cook_downloading: '⏳ جاري تنزيل {count} ملف...',
        cook_processing: '✅ تم تنزيل *{count}* ملف\n🍪 الفئة: *{pool}*\n\n⏳ جاري المعالجة والتحقق...',
        cook_download_fail: '❌ فشل تنزيل الملفات. حاول مرة أخرى.',
        cook_checking: '⏳ جاري فحص {count} حساب...',
        cook_import_result: [
            '✅ *اكتمل الاستيراد — {source}*',
            '🍪 الفئة: *{pool}*', '',
            '• الكل: *{total}*',
            '• مُضاف جديد: *{added}*',
            '• مُستبدل (مكرر): *{replaced}*',
            '• منتهي / غير صالح: *{bad}*',
        ].join('\n'),
        cook_import_new:      '\n*حسابات جديدة:*',
        cook_import_replaced: '\n*تم استبدالها:*',

        cook_stats_title: '📊 *إحصائيات الكوكيز حسب الفئة*\n\n• إجمالي النشطة: *{active}* | المنتهية: *{expired}* | الكل: *{total}*\n',
        cook_stats_empty: '📊 لا توجد كوكيز محفوظة بعد.\n\nانتقل لـ *🍪 إدارة الكوكيز* واختر فئة لرفع كوكيز إليها.',
        cook_stats_row: '{pool}\n  🟢 نشط: {active}  |  🔴 منتهي: {expired}',
        cook_stats_header: '\n\n─── *الحسابات النشطة والحجوزات* ───',
        cook_stats_item: '• *#{id}* - {email} ({plan})\n  🛡️ الضمان: {pool} | 👥 المحجوز: *{active}/{max}* مستخدمين',


        cook_verify_start: '🔄 *جاري فحص جميع الكوكيز...*\n\nهذا قد يستغرق بعض الوقت.',
        cook_verify_result: [
            '✅ *اكتمل الفحص*', '',
            '🟢 نشطة: *{active}* | 🔴 منتهية: *{expired}* | الكل: *{total}*',
        ].join('\n'),
        cook_verify_expired:  '\n*🔴 منتهية:*',
        cook_verify_expiring: '\n*⚠️ تنتهي قريباً:*',
        cook_verify_empty: 'لا توجد كوكيز للفحص.',

        settings_title: '⚙️ *إعدادات النظام*\n\n• الحد الأقصى للمستخدمين: *{max}*\n• الفحص التلقائي: *{auto}*\n• اللغة: *{lang}*\n• البروكسي: *{proxy}*\n\nاختر الإعداد للتعديل:',
        btn_set_max:  '👥 تعديل الحد الأقصى للمستخدمين',
        btn_set_auto: '⏱️ جدولة الفحص التلقائي',
        btn_set_lang: '🌐 Language / اللغة / Langue',
        btn_set_proxy:'🌐 إعدادات البروكسي',
        set_max_prompt: '👥 *الحد الأقصى للمستخدمين*\n\nالحالي: *{cur}* مستخدم لكل حساب.\n\nأرسل الرقم الجديد:',
        set_max_success: '✅ *تم التحديث!*\n\n• الحد الأقصى لكل حساب: *{n}* مستخدم\n• تم تطبيق الإعداد على جميع الحسابات.',
        set_auto_title: '⏱️ *الفحص التلقائي للكوكيز*\n\nالفترة الحالية: *{cur}*\n\nاختر الفترة الجديدة:',
        set_auto_disabled: '🚫 مُوقَف',
        set_auto_every: 'كل {h} ساعة',
        set_auto_btn: '⚡ كل {h}س',
        set_auto_off: '🚫 إيقاف',
        set_auto_success: '✅ *تم التحديث!*\n\n• الفحص التلقائي: *{val}*',
        set_lang_title: '🌐 *اختيار اللغة*\n\nاختر اللغة المفضلة:',
        set_lang_success: '✅ تم تغيير اللغة إلى *{lang}*',
        auto_check_label: 'كل {h} ساعة',
        auto_check_off: 'مُوقَف',

        // Proxy (Arabic)
        proxy_menu_title: '🌐 *إعدادات البروكسي*\n\n• الحالة: *{status}*\n• الوضع: *{mode}*\n• الرابط: `{url}`\n• الأخطاء: *{fails}/{max}*\n\nاختر العملية:',
        proxy_status_on:    '🟢 مُفعَّل',
        proxy_status_off:   '🔴 مُوقَف',
        proxy_mode_proxy:   '🌐 عبر البروكسي',
        proxy_mode_local:   '🏠 IP محلي',
        proxy_url_none:     'غير مُعيَّن',
        btn_proxy_check_ip: '🔍 فحص IP الحالي',
        btn_proxy_add:      '➕ إضافة / استبدال بروكسي',
        btn_proxy_enable:   '🟢 تفعيل البروكسي',
        btn_proxy_disable:  '🔴 إيقاف البروكسي',
        btn_proxy_delete:   '🗑️ حذف البروكسي',
        btn_proxy_local:    '🏠 استخدام IP محلي',
        proxy_add_prompt:   '➕ *إضافة / استبدال بروكسي*\n\nأرسل رابط البروكسي بأحد الصيغ التالية:\n• `http://host:port`\n• `http://user:pass@host:port`\n• `socks5://host:port`\n• `socks5://user:pass@host:port`',
        proxy_testing:      '⏳ جاري اختبار اتصال البروكسي...',
        proxy_test_ok:      '✅ *تم الاتصال بالبروكسي!*\n\n• IP عبر البروكسي: `{ip}`\n• تم حفظ البروكسي وتفعيله.',
        proxy_test_fail:    '❌ *فشل اختبار البروكسي*\n\nالخطأ: `{error}`\n\nتحقق من الرابط وحاول مرة أخرى.',
        proxy_invalid_url:  '❌ رابط بروكسي غير صالح: `{reason}`\n\nأعد المحاولة:',
        proxy_enabled_ok:   '✅ تم *تفعيل* البروكسي. جميع الطلبات ستمر عبره.',
        proxy_disabled_ok:  '✅ تم *إيقاف* البروكسي. يستخدم IP محلي الآن.',
        proxy_deleted_ok:   '✅ تم حذف البروكسي بنجاح.',
        proxy_checking_ip:  '⏳ جاري فحص عنوان IP...',
        proxy_ip_result:    '🌐 *عنوان IP الحالي*\n\n• الوضع: *{mode}*\n• IP: `{ip}`',
        proxy_ip_fail:      '❌ تعذر تحديد عنوان IP.',
        proxy_fallback_alert: '⚠️ *تنبيه: فشل البروكسي*\n\nفشل البروكسي `{url}` *{fails}* مرات متتالية.\n\n🔄 تم التحويل تلقائياً إلى وضع *IP المحلي*.\n\nيرجى تحديث أو حذف البروكسي من ⚙️ الإعدادات → 🌐 البروكسي.',
        proxy_no_proxy:     'غير مُعيَّن',

        plan_label: { Premium: '👑 Premium 4K', Standard: '📺 Standard 1080p', Basic: '📱 Basic', TV: '🖥️ TV Screen' },
        pool_label: {
            no_warranty: '🚫 بدون ضمان',
            '7_days':    '⚡ 7 أيام',
            '1_month':   '🗓️ شهر واحد',
            '2_months':  '🗓️ شهرين',
            '3_months':  '🗓️ 3 أشهر',
            '6_months':  '🗓️ 6 أشهر',
            '1_year':    '👑 سنة كاملة',
        },
        alloc_random:   '🎲 عشوائي من الحوض (افتراضي)',
        alloc_specific: '📌 حساب محدد',
        error_db:       '❌ خطأ في قاعدة البيانات.',
        error_number:   '❌ أدخل رقماً صحيحاً أكبر من صفر:',
        unauthorized:   '🚫 غير مصرح لك.',
        // Customer strings (Arabic)
        cust_select_lang: '👋 أهلاً بك! الرجاء اختيار لغة البوت المفضلة:',
        cust_join_channel: '❌ يجب عليك الاشتراك في القناة أولاً لتتمكن من استخدام البوت:\n👉 {channel}\n\nبعد الاشتراك، اضغط على زر التحقق أدناه:',
        cust_btn_verify: '✅ التحقق من الاشتراك',
        cust_btn_verify_success: '🎉 شكراً لك على الاشتراك! حصلت على 1 نقطة.',
        cust_main_menu: '🎬 <b>بوابة تفعيل أكواد نتفليكس</b>\n\n💰 <b>نقاطك الحالية:</b> {points}\n👥 <b>تقدم الإحالات:</b> {ref_count}/3\n\n🔗 <b>رابط الإحالة الخاص بك:</b>\n<code>{ref_link}</code>',
        cust_btn_get_cdk: '🎁 الحصول على كود تفعيل',
        cust_btn_lang: '🌐 تغيير اللغة',
        cust_btn_support: '📞 الدعم الفني',
        cust_btn_back: '⬅️ رجوع',
        cust_support_msg: '📩 لأي استفسارات أو دعم، تواصل مع الإدارة هنا: {admin}',
        cust_cookies_updated: '🎉 <b>تمت إضافة حسابات نتفليكس جديدة في البوت!</b> 🎬🍿\n\nماذا تنتظر؟ شارك البوت واجمع النقاط للحصول على كود التفعيل الخاص بك مجاناً! 🎁👇\n\nرابط إحالتك المباشر:\n<code>{ref_link}</code>',
        cust_daily_broadcast: '⚡ <b>ماذا تنتظر؟</b> شارك رابط إحالتك واجمع النقاط للحصول على حساب نتفليكس مجاناً! 🎬🎁\n\nرابط إحالتك المباشر:\n<code>{ref_link}</code>',
        cust_left_channel_warning: '⚠️ <b>غادرت القناة!</b>\n\nنقاطك: <b>{points}</b> (-1 عقوبة)\n\nارجع للقناة لاستعادة نقطتك.',
        cust_rejoined_channel: '👋 <b>أهلاً بعودتك!</b>\n\nنقاطك: <b>{points}</b>\n\n❌ لا كود CDK جديد — غادرت القناة من قبل.',
        cust_not_enough_points: '❌ ليس لديك نقاط كافية (مطلوب 1 نقطة).\n\nقم بدعوة 3 أصدقاء للحصول على 1 نقطة! شارك رابط إحالتك:\n<code>{ref_link}</code>',
        cust_ref_notify: '🔔 انضم شخص جديد للبوت عبر رابط الإحالة الخاص بك! ({ref_count}/3 دعوات للحصول على نقطة)\n💰 نقاطك الحالية: <b>{points}</b>',
        cust_ref_point_reward: '🎉 تهانينا! قمت بدعوة 3 أصدقاء وحصلت على 1 نقطة! مجموع نقاطك: {points}',
        cust_cdk_success: '🔑 <b>كود تفعيل نتفليكس الخاص بك:</b>\n\n<code>{key}</code>\n\nالفئة: <b>{plan}</b>\n\n👉 اذهب إلى our portal لتفعيله واستلام الحساب!',
        admin_btn_analytics: '👥 إحصائيات المشتركين',
        admin_analytics_title: '📊 *إحصائيات المشتركين*\n\n👥 إجمالي الزبائن المسجلين: *{total_users}*\n💰 إجمالي النقاط الموزعة: *{total_points}*\n\n📋 *أحدث الأعضاء:*',
        admin_analytics_user_row: '👤 @{username} (ID: `{id}`) | النقاط: *{points}* | الإحالات: *{invites}* | تاريخ الدخول: {date}',

    },

    // ─────────────────────────────────────────────
    // FRENCH
    // ─────────────────────────────────────────────
    fr: {
        main_title: '🎬 *NETVXL — Console de Gestion*',
        main_body: [
            '',
            '👋 Bienvenue dans le système de gestion Netflix CDK',
            '',
            '🔑 *CDK* — Créer et gérer les clés d\'abonnement',
            '🍪 *Cookies* — Importer et vérifier les comptes Netflix',
            '⚙️ *Paramètres* — Configurer la vérification auto et les limites',
        ].join('\n'),

        btn_cdk:      '🔑 Gestion CDK',
        btn_cookies:  '🍪 Gestion Cookies',
        btn_settings: '⚙️ Paramètres',
        btn_users: '👥 Gestion Utilisateurs',
        btn_back:     '⬅️ Retour au Menu',
        btn_back_users: '⬅️ Retour Utilisateurs',
        btn_back_cdk:     '⬅️ Retour CDK',
        btn_back_cookies: '⬅️ Retour Cookies',
        btn_back_settings:'⬅️ Retour Paramètres',
        btn_home:     '⬅️ Menu Principal',
        btn_cancel:   '❌ Annuler',
        btn_confirm:  '✅ Confirmer',

        cdk_menu_title: '🔑 *Gestion des Clés CDK*\n\nChoisissez une action:',
        btn_cdk_create:     '➕ Créer des clés CDK',
        btn_cdk_check:      '🔍 Vérifier une clé CDK',
        btn_cdk_list:       '📋 50 Dernières clés',
        btn_cdk_delete:     '❌ Supprimer une clé',
        btn_cdk_delete_all: '🗑️ Tout supprimer',

        cdk_create_step1: '🔑 *Créer des clés CDK*\n\n*Étape 1/4:* Choisissez le type d\'abonnement:',
        cdk_create_step2: '🔑 *Créer des clés CDK*\n\n✅ Abonnement: *{plan}*\n\n*Étape 2/4:* Choisissez la durée de garantie:',
        cdk_create_step3: '🔑 *Créer des clés CDK*\n\n✅ Abonnement: *{plan}*\n✅ Garantie: *{warranty}*\n\n*Étape 3/4:* Choisissez le mode d\'allocation:',
        cdk_create_step3_random: '🔑 *Créer des clés CDK*\n\n✅ Abonnement: *{plan}*\n✅ Garantie: *{warranty}*\n✅ Mode: *🎲 Aléatoire du pool*\n\n*Étape 4/4:* Choisissez la quantité:',
        cdk_create_step3_specific: '🔑 *Créer des clés CDK*\n\n✅ Abonnement: *{plan}*\n✅ Garantie: *{warranty}*\n✅ Mode: *📌 Compte spécifique*\n\nChoisissez le compte Netflix:',
        cdk_create_step4_bound: '🔑 *Créer des clés CDK*\n\n✅ Abonnement: *{plan}*\n✅ Garantie: *{warranty}*\n✅ Compte: *{id}*\n\n*Étape 4/4:* Choisissez la quantité:',
        cdk_create_custom_qty: '🔑 *Créer des clés CDK*\n\n✅ Abonnement: *{plan}*\n✅ Garantie: *{warranty}*\n\n✏️ Envoyez le nombre de clés à générer:',
        cdk_no_active_accounts: '❌ Aucun compte actif trouvé pour la liaison.\n\nChoisissez l\'allocation aléatoire.',
        cdk_generated: '🔑 *{count} Clé(s) CDK Générée(s)*\n\n✅ Abonnement: *{plan}*\n🛡️ Garantie: *{warranty}*\n📅 Durée: *{duration}*\n{bind}\n\n{keys}',
        cdk_bind_random: '\n🎲 *Allocation:* Aléatoire du pool',
        cdk_bind_specific: '\n📌 *Compte lié:* {id}',
        cdk_duration_unlimited: 'Illimitée',
        cdk_duration_days: '{days} jours',

        cdk_list_title: '📋 *{count} Dernières Clés CDK:*\n\n',
        cdk_list_empty: 'Aucune clé CDK trouvée.',

        cdk_check_prompt: '🔍 *Vérifier une clé CDK*\n\nEnvoyez la clé à vérifier:',
        cdk_check_notfound: '❌ Clé `{key}` introuvable.',
        cdk_check_result: [
            '🔑 *Détails de la clé*', '',
            '🔑 Clé: `{key}`',
            '📋 Abonnement: *{plan}*',
            '{icon} Statut: *{status}*',
            '🛡️ Garantie: *{warranty}*',
            '👥 Appareils: *{active}/{max}*',
            '📱 Utilisé sur: *{device}*',
            '📧 Compte: {email}',
            '📅 Créé le: *{date}*',
        ].join('\n'),
        cdk_status_unused: 'Non utilisé',
        cdk_status_used:   'Utilisé',
        cdk_device_none:   'Pas encore utilisé',
        cdk_email_none:    'Non attribué',

        cdk_delete_prompt: '❌ *Supprimer une clé CDK*\n\nEnvoyez la clé à supprimer:',
        cdk_delete_success: '✅ Clé `{key}` supprimée avec succès.',
        cdk_delete_notfound: '❌ Clé `{key}` introuvable.',

        cdk_delete_all_confirm: '⚠️ *Attention!*\n\nToutes les clés CDK et les journaux d\'activation seront définitivement supprimés.\n\nÊtes-vous sûr?',
        cdk_delete_all_success: '✅ Toutes les clés CDK et les journaux ont été supprimés.',

        cookies_menu_title: '🍪 *Gestion des Cookies*\n\nChoisissez un pool pour importer des cookies ou consultez les stats:',
        btn_cook_stats:  '📊 Statistiques Cookies',
        btn_cook_verify: '🔄 Vérifier tous les comptes',
        btn_cook_dead_cdks: '⚠️ Compensation (Cookies Morts)',
        btn_cook_delete: '❌ Supprimer Compte (Cookie)',
        btn_cook_delete_all: '🗑️ Supprimer tous les Cookies',
        btn_cook_delete_dead: '🗑️ Supprimer uniquement les cookies expirés',
        btn_cook_divider:'─── Importer par Catégorie ───',
        cook_delete_prompt: '❌ *Supprimer Compte (Cookie)*\n\nEnvoyez l\'adresse Email du compte à supprimer :',
        cook_delete_success: '✅ Compte `{email}` supprimé avec succès.',
        cook_delete_notfound: '❌ Compte avec Email `{email}` introuvable.',
        cook_delete_all_confirm: '⚠️ *Attention!*\n\nCela supprimera définitivement TOUS les fichiers cookies du système.\n\nÊtes-vous sûr de vouloir continuer?',
        cook_delete_all_success: '✅ Suppression réussie de tous les cookies ({count} comptes).',
        cook_delete_dead_success: '✅ Suppression réussie de {count} cookies expirés.',
        cook_delete_dead_empty: 'ℹ️ Aucun cookie expiré trouvé à supprimer.',
        cook_stats_title: '📊 *Comptes Actifs & Slots*\n\nSélectionnez un compte ci-dessous pour afficher les détails, modifier la capacité de slots, changer de pool ou le supprimer :',
        cook_manage_title: '📧 *Gérer le Compte*\n\n📧 Email: `{email}`\n📋 Offre: *{plan}*\n🛡️ Garantie: *{pool}*\n👥 Capacité: *{active}/{max}* utilisateurs\n📅 Facturation Netflix: *{billing}*',
        cook_manage_billing_days: '`{date}` (*{days} jours restants*)',
        cook_manage_billing_unknown: '`{date}` (*Facturation partenaire / Inconnu*)',
        btn_cook_change_slots: '👥 Modifier la limite de slots',
        btn_cook_change_pool: '🛡️ Modifier le pool de garantie',
        btn_cook_verify_single: '🔄 Vérifier ce compte',
        btn_cook_back_list: '🔙 Retour aux comptes',
        cook_verify_single_start: '⏳ *Vérification du compte `{email}`...*',
        cook_verify_single_ok: '✅ *Le compte `{email}` est Actif & Fonctionnel !*\n\n📋 Offre: *{plan}*\n📅 Expiry: *{billing}*',
        cook_verify_single_fail: '❌ *Le compte `{email}` est Mort / Expiré !*\n\nStatut mis à jour comme Expiré.',
        cook_change_slots_prompt: '👥 *Modifier la limite de slots*\n\nEnvoyez la nouvelle limite de slots (ex: 5, 10, 15, 20) pour le compte `{email}`:',
        cook_change_slots_success: '✅ Capacité de slots mise à jour à *{n}* pour le compte `{email}`.',
        cook_change_pool_title: '🛡️ *Modifier le pool de garantie*\n\nSélectionnez le nouveau pool pour le compte `{email}`:',
        cook_change_pool_success: '✅ Compte `{email}` déplacé dans le pool *{pool}* avec succès.',
        cook_delete_one_confirm: '⚠️ *Confirmation de suppression*\n\nÊtes-vous sûr de vouloir supprimer le compte `{email}`? Toutes ses clés CDK associées seront détachées !',

        // User Management (French)
        users_title: '👥 *Gestion des Utilisateurs*\n\nIci vous pouvez ajouter des partenaires ou des créateurs CDK :',
        btn_users_add_partner: '➕ Ajouter Partenaire',
        btn_users_add_creator: '➕ Ajouter Créateur CDK',
        btn_users_list: '📋 Liste des Utilisateurs',
        btn_users_delete: '❌ Retirer Utilisateur',
        users_add_partner_prompt: '👤 *Ajouter Partenaire*\n\nEnvoyez le Chat ID Telegram du partenaire à ajouter :',
        users_add_creator_prompt: '👤 *Ajouter Créateur CDK*\n\nEnvoyez le Chat ID Telegram du créateur à ajouter :',
        users_delete_prompt: '❌ *Retirer Utilisateur*\n\nEnvoyez le Chat ID Telegram de l\'utilisateur à retirer :',
        users_add_success: '✅ L\'utilisateur avec Chat ID \`{id}\` a été ajouté comme *{role}*.',
        users_delete_success: '✅ L\'utilisateur avec Chat ID \`{id}\` a été retiré.',
        users_list_title: '📋 *Utilisateurs Autorisés :*',
        users_list_empty: 'Aucun utilisateur autorisé.',
        users_list_row: '• ID: \`{id}\` | Rôle: *{role}* | Ajouté le: {date}',
        error_no_permission: '❌ Accès refusé. Vous n\'avez pas la permission.',
        cdk_gen_no_stock: '❌ *Génération bloquée (Pas de stock)*\n\nImpossible de générer {requested} clés.\n\nOffre: *{plan}*\nGarantie: *{warranty}*\nSlots disponibles: *{available}* slots.\n\nVeuillez d\'abord importer plus de cookies pour ce pool !',
        error_raw_cookie_paste: '❌ *Opération invalide*\n\nVous avez envoyé du texte cookie brut. Veuillez aller dans *Gestion des Cookies*, choisir le pool correspondant, et y importer vos cookies en tant que fichier !',


        // Dead CDK Compensation (French)
        cook_dead_title: '⚠️ *Compensation & Comptes Arrêtés*\n\nVoici les comptes qui ont cessé de fonctionner, avec les clés CDK associées :',
        cook_dead_empty: '✅ Aucun compte arrêté/expiré trouvé pour le moment.',
        cook_dead_row: '\n• ❌ *{email}* ({pool})\n  Vérifié: {date}\n  🔑 *Clés CDK :*',
        cook_dead_key: '    - `{key}` ({status} | Appareil: {device} | Actif: {active})',


        cook_pool_prompt: '🍪 *Importer des Cookies — {pool}*\n\n📤 Envoyez un ou plusieurs fichiers .txt avec les données cookies.\n\n💡 Vous pouvez envoyer plusieurs fichiers en même temps.',
        cook_no_file: '⚠️ Veuillez d\'abord choisir une catégorie depuis *🍪 Gestion Cookies*, puis envoyez le fichier.',
        cook_downloading: '⏳ Téléchargement de {count} fichier(s)...',
        cook_processing: '✅ *{count}* fichier(s) téléchargé(s)\n🍪 Pool: *{pool}*\n\n⏳ Traitement et vérification en cours...',
        cook_download_fail: '❌ Échec du téléchargement. Veuillez réessayer.',
        cook_checking: '⏳ Vérification de {count} compte(s)...',
        cook_import_result: [
            '✅ *Importation terminée — {source}*',
            '🍪 Pool: *{pool}*', '',
            '• Total: *{total}*',
            '• Nouveaux comptes: *{added}*',
            '• Remplacés (doublon): *{replaced}*',
            '• Expirés / Invalides: *{bad}*',
        ].join('\n'),
        cook_import_new:      '\n*Nouveaux Comptes:*',
        cook_import_replaced: '\n*Remplacés:*',

        cook_stats_title: '📊 *Statistiques par Pool*\n\n• Total Actifs: *{active}* | Expirés: *{expired}* | Total: *{total}*\n',
        cook_stats_empty: '📊 Aucun cookie enregistré.\n\nAllez dans *🍪 Gestion Cookies* et choisissez un pool.',
        cook_stats_row: '{pool}\n  🟢 Actifs: {active}  |  🔴 Expirés: {expired}',
        cook_stats_header: '\n\n─── *Comptes Actifs & Réservations* ───',
        cook_stats_item: '• *#{id}* - {email} ({plan})\n  🛡️ Pool: {pool} | 👥 Réservé: *{active}/{max}* util.',

        cook_verify_start: '🔄 *Vérification de tous les comptes...*\n\nCela peut prendre un moment.',
        cook_verify_result: [
            '✅ *Vérification terminée*', '',
            '🟢 Actifs: *{active}* | 🔴 Expirés: *{expired}* | Total: *{total}*',
        ].join('\n'),
        cook_verify_expired:  '\n*🔴 Expirés:*',
        cook_verify_expiring: '\n*⚠️ Expirent bientôt:*',
        cook_verify_empty: 'Aucun cookie à vérifier.',

        settings_title: '⚙️ *Paramètres du Système*\n\n• Max utilisateurs/cookie: *{max}*\n• Vérification auto: *{auto}*\n• Langue: *{lang}*\n• Proxy: *{proxy}*\n\nChoisissez un paramètre:',
        btn_set_max:  '👥 Modifier le max utilisateurs',
        btn_set_auto: '⏱️ Intervalle de vérification auto',
        btn_set_lang: '🌐 Language / اللغة / Langue',
        btn_set_proxy:'🌐 Paramètres Proxy',
        set_max_prompt: '👥 *Max Utilisateurs par Cookie*\n\nLimite actuelle: *{cur}* utilisateurs par compte.\n\nEnvoyez la nouvelle limite:',
        set_max_success: '✅ *Mis à jour!*\n\n• Max utilisateurs: *{n}*\n• Appliqué à tous les comptes existants.',
        set_auto_title: '⏱️ *Vérification Auto des Cookies*\n\nIntervalle actuel: *{cur}*\n\nChoisissez le nouvel intervalle:',
        set_auto_disabled: '🚫 Désactivé',
        set_auto_every: 'Toutes les {h}h',
        set_auto_btn: '⚡ {h}h',
        set_auto_off: '🚫 Désactiver',
        set_auto_success: '✅ *Mis à jour!*\n\n• Vérification auto: *{val}*',
        set_lang_title: '🌐 *Sélection de la Langue*\n\nChoisissez votre langue:',
        set_lang_success: '✅ Langue définie sur *{lang}*',
        auto_check_label: 'Toutes les {h}h',
        auto_check_off: 'Désactivé',

        // Proxy (French)
        proxy_menu_title: '🌐 *Paramètres Proxy*\n\n• Statut: *{status}*\n• Mode: *{mode}*\n• URL: `{url}`\n• Échecs: *{fails}/{max}*\n\nChoisissez une action:',
        proxy_status_on:    '🟢 Activé',
        proxy_status_off:   '🔴 Désactivé',
        proxy_mode_proxy:   '🌐 Via Proxy',
        proxy_mode_local:   '🏠 IP Local',
        proxy_url_none:     'Non configuré',
        btn_proxy_check_ip: '🔍 Vérifier IP actuel',
        btn_proxy_add:      '➕ Ajouter / Remplacer Proxy',
        btn_proxy_enable:   '🟢 Activer le Proxy',
        btn_proxy_disable:  '🔴 Désactiver le Proxy',
        btn_proxy_delete:   '🗑️ Supprimer le Proxy',
        btn_proxy_local:    '🏠 Utiliser IP Local',
        proxy_add_prompt:   '➕ *Ajouter / Remplacer Proxy*\n\nEnvoyez l\'URL du proxy dans un de ces formats:\n• `http://host:port`\n• `http://user:pass@host:port`\n• `socks5://host:port`\n• `socks5://user:pass@host:port`',
        proxy_testing:      '⏳ Test de connexion proxy en cours...',
        proxy_test_ok:      '✅ *Proxy Connecté!*\n\n• IP via Proxy: `{ip}`\n• Proxy sauvegardé et activé.',
        proxy_test_fail:    '❌ *Échec du Test Proxy*\n\nErreur: `{error}`\n\nVérifiez l\'URL et réessayez.',
        proxy_invalid_url:  '❌ URL proxy invalide: `{reason}`\n\nRéessayez:',
        proxy_enabled_ok:   '✅ Proxy *activé*. Toutes les requêtes passeront par le proxy.',
        proxy_disabled_ok:  '✅ Proxy *désactivé*. Utilisation de l\'IP local.',
        proxy_deleted_ok:   '✅ Proxy supprimé avec succès.',
        proxy_checking_ip:  '⏳ Vérification de l\'adresse IP...',
        proxy_ip_result:    '🌐 *Adresse IP Actuelle*\n\n• Mode: *{mode}*\n• IP: `{ip}`',
        proxy_ip_fail:      '❌ Impossible de déterminer l\'adresse IP.',
        proxy_fallback_alert: '⚠️ *Alerte: Échec Proxy*\n\nLe proxy `{url}` a échoué *{fails}* fois consécutives.\n\n🔄 Basculé automatiquement en mode *IP Local*.\n\nVeuillez mettre à jour ou supprimer le proxy dans ⚙️ Paramètres → 🌐 Proxy.',
        proxy_no_proxy:     'Non configuré',

        plan_label: { Premium: '👑 Premium 4K', Standard: '📺 Standard 1080p', Basic: '📱 Basique', TV: '🖥️ Écran TV' },
        pool_label: {
            no_warranty: '🚫 Sans Garantie',
            '7_days':    '⚡ 7 Jours',
            '1_month':   '🗓️ 1 Mois',
            '2_months':  '🗓️ 2 Mois',
            '3_months':  '🗓️ 3 Mois',
            '6_months':  '🗓️ 6 Mois',
            '1_year':    '👑 1 An',
        },
        alloc_random:   '🎲 Aléatoire du Pool (Défaut)',
        alloc_specific: '📌 Compte Spécifique (Choisir ID)',
        error_db:       '❌ Erreur de base de données.',
        error_number:   '❌ Veuillez envoyer un nombre valide:',
        unauthorized:   '🚫 Non autorisé.',
        // Customer strings (French)
        cust_select_lang: '👋 Bienvenue ! Veuillez choisir votre langue / الرجاء اختيار لغة البوت:',
        cust_join_channel: '🚫 Vous devez d\'abord vous abonner à notre chaîne pour utiliser le robot :',
        cust_btn_verify: '✅ Vérifier l\'abonnement',
        cust_btn_verify_success: '🎉 Merci d\'avoir rejoint ! Vous avez reçu 1 point.',
        cust_main_menu: '🎬 <b>Netflix CDK Portail</b>\n\n💰 <b>Vos points:</b> {points}\n👥 <b>Progrès des invitations:</b> {ref_count}/3\n\n🔗 <b>Votre lien de parrainage:</b>\n<code>{ref_link}</code>',
        cust_btn_get_cdk: '🎁 Obtenir la clé CDK',
        cust_btn_lang: '🌐 Changer de langue',
        cust_btn_support: '📞 Support',
        cust_btn_back: '⬅️ Retour',
        cust_support_msg: '📩 Pour toute demande, contactez l\'administrateur : {admin}',
        cust_cookies_updated: '🎉 <b>De nouveaux comptes Netflix ont été ajoutés au bot !</b> 🎬🍿\n\nQu\'attendez-vous ? Partagez le bot et collectez des points pour obtenir votre clé d\'activation gratuitement ! 🎁👇\n\nVotre lien de parrainage :\n<code>{ref_link}</code>',
        cust_daily_broadcast: '⚡ <b>Qu\'attendez-vous ?</b> Partagez votre lien de parrainage et collectez des points pour obtenir un compte Netflix gratuit ! 🎬🎁\n\nVotre lien de parrainage :\n<code>{ref_link}</code>',
        cust_left_channel_warning: '⚠️ <b>Vous avez quitté le canal!</b>\n\nPoints: <b>{points}</b> (-1)\n\nRejoignez pour récupérer votre point.',
        cust_rejoined_channel: '👋 <b>Bienvenue!</b>\n\nPoints: <b>{points}</b>\n\n❌ Pas de nouveau CDK — vous avez quitté avant.',
        cust_not_enough_points: '❌ Points insuffisants (1 point requis).\n\nInvitez 3 amis pour gagner 1 point : <code>{ref_link}</code>',
        cust_ref_notify: '🔔 Quelqu\'un a rejoint via votre lien ! ({ref_count}/3 invitations pour le prochain point)\n💰 Vos points actuels : <b>{points}</b>',
        cust_ref_point_reward: '🎉 Félicitations ! Vous avez invité 3 amis et gagné 1 point ! Total : {points}',
        cust_cdk_success: '🔑 <b>Votre clé CDK Netflix :</b>\n\n<code>{key}</code>\n\nPlan: <b>{plan}</b>\n\n👉 Visitez our portal pour l\'activer !',
        admin_btn_analytics: '👥 Statistiques Clients',
        admin_analytics_title: '📊 *Statistiques Clients*\n\n👥 Total clients enregistrés: *{total_users}*\n💰 Total points distribués: *{total_points}*\n\n📋 *Derniers membres:*',
        admin_analytics_user_row: '👤 @{username} (ID: `{id}`) | Points: *{points}* | Invitations: *{invites}* | Rejoint: {date}',

    },

    // ─────────────────────────────────────────────
    // CHINESE (zh)
    // ─────────────────────────────────────────────
    zh: {
        unauthorized: '🚫 未授权。',
        error_db: '❌ 数据库错误。',
        cust_select_lang: '👋 欢迎！请选择您的语言 / الرجاء اختيار لغة البوت:',
        cust_join_channel: '🚫 您必须先订阅我们的频道才能使用机器人：',
        cust_btn_verify: '✅ 验证关注',
        cust_btn_verify_success: '🎉 感谢您的加入！您获得了 1 个积分。',
        cust_main_menu: '🎬 <b>Netflix CDK 门户</b>\n\n💰 <b>您的积分:</b> {points}\n👥 <b>邀请进度:</b> {ref_count}/3\n\n🔗 <b>您的专属邀请链接:</b>\n<code>{ref_link}</code>',
        cust_btn_get_cdk: '🎁 获取 CDK 激活码',
        cust_btn_lang: '🌐 切换语言',
        cust_btn_support: '📞 联络支持',
        cust_btn_back: '⬅️ 返回',
        cust_support_msg: '📩 如需任何帮助，请联系管理员：{admin}',
        cust_cookies_updated: '🎉 <b>机器人中已添加新的 Netflix 账号！</b> 🎬🍿\n\n你还在等什么？分享机器人并收集积分，免费获取您的激活码！ 🎁👇\n\n您的专属邀请链接：\n<code>{ref_link}</code>',
        cust_daily_broadcast: '⚡ <b>你还在等什么？</b>分享你的专属邀请链接并赚取积分，免费换取 Netflix 账号！🎬🎁\n\n您的专属邀请链接：\n<code>{ref_link}</code>',
        cust_not_enough_points: '❌ 积分不足（需要 1 积分）。\n\n邀请 3 名好友即可获得 1 积分！分享您的邀请链接：\n<code>{ref_link}</code>',
        cust_ref_notify: '🔔 有人通过您的链接加入了机器人！({ref_count}/3 邀请进度，满 3 可得积分)\n💰 您当前的积分：<b>{points}</b>',
        cust_ref_point_reward: '🎉 恭喜！您成功邀请了 3 位好友，获得 1 积分！总积分：{points}',
        cust_cdk_success: '🔑 <b>您的 Netflix CDK 激活码:</b>\n\n<code>{key}</code>\n\n套餐: <b>{plan}</b>\n\n👉 前往 our portal 激活使用！',
        admin_btn_analytics: '👥 客户分析',
        admin_analytics_title: '📊 *客户分析*\n\n👥 总注册客户: *{total_users}*\n💰 总分配积分: *{total_points}*\n\n📋 *最新用户:*',
        admin_analytics_user_row: '👤 @{username} (ID: `{id}`) | 积分: *{points}* | 邀请: *{invites}* | 加入: {date}',
    },


    // ─────────────────────────────────────────────
    // RUSSIAN (ru)
    // ─────────────────────────────────────────────
    ru: {
        unauthorized: '🚫 Доступ запрещен.',
        error_db: '❌ Ошибка базы данных.',
        cust_select_lang: '👋 Добро пожаловать! Пожалуйста, выберите язык / الرجاء اختيار لغة البوت:',
        cust_join_channel: '🚫 Вы должны сначала подписаться на наш канал, чтобы использовать бота:',
        cust_btn_verify: '✅ Проверить подписку',
        cust_btn_verify_success: '🎉 Спасибо за подписку! Вы получили 1 балл.',
        cust_main_menu: '🎬 <b>Netflix CDK Портал</b>\n\n💰 <b>Ваши баллы:</b> {points}\n👥 <b>Прогресс приглашений:</b> {ref_count}/3\n\n🔗 <b>Ваша ссылка для приглашения:</b>\n<code>{ref_link}</code>',
        cust_btn_get_cdk: '🎁 Получить CDK ключ',
        cust_btn_lang: '🌐 Изменить язык',
        cust_btn_support: '📞 Поддержка',
        cust_btn_back: '⬅️ Назад',
        cust_support_msg: '📩 Для связи с администратором: {admin}',
        cust_cookies_updated: '🎉 <b>В бота были добавлены новые аккаунты Netflix!</b> 🎬🍿\n\nЧего вы ждете? Поделитесь ботом и копите баллы для получения бесплатного ключа активации! 🎁👇\n\nВаша ссылка для приглашения:\n<code>{ref_link}</code>',
        cust_daily_broadcast: '⚡ <b>Чего вы ждете?</b> Поделитесь своей ссылкой для приглашения и копите баллы для получения бесплатного аккаунта Netflix! 🎬🎁\n\nВаша ссылка для приглашения:\n<code>{ref_link}</code>',
        cust_not_enough_points: '❌ Недостаточно баллов (требуется 1 балл).\n\nПригласите 3 друзей, чтобы получить 1 балл: <code>{ref_link}</code>',
        cust_ref_notify: '🔔 Кто-то присоединился по вашей ссылке! ({ref_count}/3 приглашений до следующего балла)\n💰 Ваши текущие баллы: <b>{points}</b>',
        cust_ref_point_reward: '🎉 Поздравляем! Вы пригласили 3 друзей и получили 1 балл! Всего баллов: {points}',
        cust_cdk_success: '🔑 <b>Ваш CDK ключ Netflix:</b>\n\n<code>{key}</code>\n\nТариф: <b>{plan}</b>\n\n👉 Перейдите на our portal для активации!',
        admin_btn_analytics: '👥 Аналитика клиентов',
        admin_analytics_title: '📊 *Аналитика клиентов*\n\n👥 Всего зарегистрированных клиентов: *{total_users}*\n💰 Всего распределенных баллов: *{total_points}*\n\n📋 *Последние пользователи:*',
        admin_analytics_user_row: '👤 @{username} (ID: `{id}`) | Баллы: *{points}* | Приглашено: *{invites}* | Присоединился: {date}',
    },

};

// Language names for display
const LANG_NAMES = {
    en: '🇬🇧 English',
    ar: '🇸🇦 العربية',
    fr: '🇫🇷 Français',
    zh: '🇨🇳 中文',
    ru: '🇷🇺 Русский',
};

/**
 * Get the string for a given key in the given language.
 * Falls back to English if the key doesn't exist in the chosen language.
 * @param {string} lang  - 'en' | 'ar' | 'fr'
 * @param {string} key   - string key
 * @param {object} [vars] - optional replacement variables e.g. { plan: 'Premium' }
 */
function t(lang, key, vars = {}) {
    const dict   = STRINGS[lang] || STRINGS['en'];
    const fallback = STRINGS['en'];
    let str = dict[key] !== undefined ? dict[key] : (fallback[key] || `[${key}]`);

    // Replace {variable} placeholders
    Object.entries(vars).forEach(([k, v]) => {
        str = str.replace(new RegExp(`\\{${k}\\}`, 'g'), v ?? '');
    });
    return str;
}

module.exports = { STRINGS, LANG_NAMES, t };
